# Application
spring.application.name=workflow360-backend
spring.profiles.default=local

# Server
server.port=8080
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=30s

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never
management.info.env.enabled=true

# Application information
info.application.name=WorkFlow360 Backend
info.application.architecture=Modular Monolith
info.application.version=0.0.1-SNAPSHOT